# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attached_device',
            new_name='AttachedDevices',
        ),
    ]
