---
# tasks file for rpi-grafana
- name: ensure grafana is installed
  command: dpkg-query -W grafana
  register: grafana_check_deb
  failed_when: grafana_check_deb.rc > 1
  changed_when: grafana_check_deb.rc == 1
  tags:
    - installation
    - configuration

- name: Download grafana package
  get_url:
    url="{{ grafana_deb_url }}"
    dest="/tmp/grafana.deb"
  when: grafana_check_deb.rc == 1
  tags:
    - installation

- name: Install my_package
  apt: deb="/tmp/grafana.deb"
  become: true
  when: grafana_check_deb.rc == 1
  tags:
    - installation






