# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attached_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('am2302', 'am2302'), ('dht11', 'dht11'), ('dht22', 'dht22'), ('sensehat', 'sense hat')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
