---
# tasks file for rpi-graphite
# Graphite API: http://graphite-api.readthedocs.io/en/latest/installation.html
- name: Install packages and dependencies
  action: apt name={{ item }} state=present
  with_items:
    - graphite-carbon
    - build-essential
    - python-dev
    - libcairo2-dev
    - libffi-dev
    - python3-pip
    - supervisor
  tags:
    - installation

- name: Install graphite-api
  pip:
    name: graphite-api
    executable: pip3
  tags:
    - installation

- name: Install gunicorn
  pip:
    name: gunicorn
    version: 19.6.0
    executable: pip3
  tags:
    - installation

- name: Systemd | Configure process watcher for graphite-api
  template:
    src: templates/graphite-api.service.j2
    dest: "/etc/systemd/system/graphite-api.service"
    owner: root
    group: root
    mode: 0644
  notify: restart graphite-api
  tags:
    - configuration

- name: Systemd | Configure process watcher for graphite-api
  copy:
    src: files/systemd/graphite-api.yaml
    dest: /etc/graphite-api.yaml
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
  notify:
    - restart graphite-api

- name: Systemd | Configure process watcher for graphite-api
  template:
    src: templates/graphite-api.socket.j2
    dest: "/etc/systemd/system/graphite-api.socket"
    owner: root
    group: root
    mode: 0644
  notify: restart graphite-api
  tags:
    - configuration

- name: Ensure graphite-api is started and is started on boot.
  service: name=graphite-api state=started enabled=yes

- name: Nginx | Configure graphite-api upstream
  template:
    src: templates/nginx-graphite-api.conf.j2
    dest: "{{nginx_sites_available}}/{{nginx_graphite_site}}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags:
    - configuration

- name: Nginx | Enablin site graphite-api
  file: src={{nginx_sites_available}}/{{nginx_graphite_site}} dest={{nginx_sites_enabled}}/{{nginx_graphite_site}} state=link
  notify: restart nginx

